[package]
name = "draw-fractal-dispatching-work-to-a-thread-pool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
num = "0.4.1"
num_cpus = "1.16.0"
threadpool = "1.8.1"
