[package]
name = "calculate-SHA256-sum-of-iso-files-concurrently"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.16.0"
ring = "0.17.7"
threadpool = "1.8.1"
walkdir = "2.4.0"
